//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using Model;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelDBContext : DbContext
    {
        public TravelDBContext()
            : base("name=TravelDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<ACC> ACCs { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<AddressExtension> AddressExtensions { get; set; }
        public virtual DbSet<ADT> ADTs { get; set; }
        public virtual DbSet<AIC> AICs { get; set; }
        public virtual DbSet<AMC> AMCs { get; set; }
        public virtual DbSet<ARC> ARCs { get; set; }
        public virtual DbSet<AwardType> AwardTypes { get; set; }
        public virtual DbSet<BaseByGuestAmt> BaseByGuestAmts { get; set; }
        public virtual DbSet<BED> BEDs { get; set; }
        public virtual DbSet<BookRule> BookRules { get; set; }
        public virtual DbSet<BUS> Buses { get; set; }
        public virtual DbSet<CancelPenalty> CancelPenalties { get; set; }
        public virtual DbSet<CategoryCodeHotelMapping> CategoryCodeHotelMappings { get; set; }
        public virtual DbSet<CCT> CCTs { get; set; }
        public virtual DbSet<CDT> CDTs { get; set; }
        public virtual DbSet<CFC> CFCs { get; set; }
        public virtual DbSet<CHG> CHGs { get; set; }
        public virtual DbSet<CXR> CXRs { get; set; }
        public virtual DbSet<DEC> DECs { get; set; }
        public virtual DbSet<DNA> DNAs { get; set; }
        public virtual DbSet<DSP> DSPs { get; set; }
        public virtual DbSet<DTB> DTBs { get; set; }
        public virtual DbSet<EAT> EATs { get; set; }
        public virtual DbSet<EWT> EWTs { get; set; }
        public virtual DbSet<EXH> EXHs { get; set; }
        public virtual DbSet<Fee> Fees { get; set; }
        public virtual DbSet<FMT> FMTs { get; set; }
        public virtual DbSet<FQC> FQCs { get; set; }
        public virtual DbSet<FTT> FTTs { get; set; }
        public virtual DbSet<GRI> GRIs { get; set; }
        public virtual DbSet<GuaranteePolicy> GuaranteePolicies { get; set; }
        public virtual DbSet<GuestRoom> GuestRooms { get; set; }
        public virtual DbSet<HAC> HACs { get; set; }
        public virtual DbSet<HACHATMapping> HACHATMappings { get; set; }
        public virtual DbSet<HAT> HATs { get; set; }
        public virtual DbSet<HOC> HOCs { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelAwardMapping> HotelAwardMappings { get; set; }
        public virtual DbSet<HST> HSTs { get; set; }
        public virtual DbSet<ImageItem> ImageItems { get; set; }
        public virtual DbSet<INF> INFs { get; set; }
        public virtual DbSet<LOC> LOCs { get; set; }
        public virtual DbSet<MCC> MCCs { get; set; }
        public virtual DbSet<OTC> OTCs { get; set; }
        public virtual DbSet<PAC> PACs { get; set; }
        public virtual DbSet<PCT> PCTs { get; set; }
        public virtual DbSet<PIC> PICs { get; set; }
        public virtual DbSet<PMT> PMTs { get; set; }
        public virtual DbSet<Policy> Policies { get; set; }
        public virtual DbSet<PolicyInfo> PolicyInfoes { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<PRT> PRTs { get; set; }
        public virtual DbSet<PRX> PRXes { get; set; }
        public virtual DbSet<PST> PSTs { get; set; }
        public virtual DbSet<PTT> PTTs { get; set; }
        public virtual DbSet<QCC> QCCs { get; set; }
        public virtual DbSet<QST> QSTs { get; set; }
        public virtual DbSet<Rate> Rates { get; set; }
        public virtual DbSet<RateExtension> RateExtensions { get; set; }
        public virtual DbSet<RatePlan> RatePlans { get; set; }
        public virtual DbSet<RBP> RBPs { get; set; }
        public virtual DbSet<REF> REFs { get; set; }
        public virtual DbSet<RefPoint> RefPoints { get; set; }
        public virtual DbSet<RGC> RGCs { get; set; }
        public virtual DbSet<RMA> RMAs { get; set; }
        public virtual DbSet<RMARoomMapping> RMARoomMappings { get; set; }
        public virtual DbSet<RoomExtension> RoomExtensions { get; set; }
        public virtual DbSet<RoomPlanBookRuleMapping> RoomPlanBookRuleMappings { get; set; }
        public virtual DbSet<RTC> RTCs { get; set; }
        public virtual DbSet<SEG> SEGs { get; set; }
        public virtual DbSet<TextItem> TextItems { get; set; }
        public virtual DbSet<UIT> UITs { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<Zone> Zones { get; set; }
        public virtual DbSet<ZoneHotelMapping> ZoneHotelMappings { get; set; }
        public virtual DbSet<Offer> Offers { get; set; }
        public virtual DbSet<OfferRule> OfferRules { get; set; }
    }
}
