// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `db`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=PC\SQLEXPRESS;database=TravelDB;integrated security=True`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace Travelling.Models
{
    /// <summary>
    /// A class which represents the RatePlan table.
    /// </summary>
	[Table("RatePlan")]
	public partial class RatePlan
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? RatePlanCode { get; set; }
		public virtual string RatePlanCategory { get; set; }
		public virtual bool? IsCommissionable { get; set; }
		public virtual bool? RateReturn { get; set; }
		public virtual string MarketCode { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual IEnumerable<RoomPlanBookRuleMapping> RoomPlanBookRuleMapping { get; set; }
		public virtual IEnumerable<Rate> Rate { get; set; }
	}

    /// <summary>
    /// A class which represents the RBP table.
    /// </summary>
	[Table("RBP")]
	public partial class RBP
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the REF table.
    /// </summary>
	[Table("REF")]
	public partial class REF
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the RGC table.
    /// </summary>
	[Table("RGC")]
	public partial class RGC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the RMA table.
    /// </summary>
	[Table("RMA")]
	public partial class RMA
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
		public virtual IEnumerable<RMARoomMapping> RMARoomMapping { get; set; }
	}

    /// <summary>
    /// A class which represents the RMARoomMapping table.
    /// </summary>
	[Table("RMARoomMapping")]
	public partial class RMARoomMapping
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? RoomID { get; set; }
		public virtual int? RMAID { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual GuestRoom GuestRoom { get; set; }
		public virtual RMA RMA { get; set; }
	}

    /// <summary>
    /// A class which represents the RoomExtension table.
    /// </summary>
	[Table("RoomExtension")]
	public partial class RoomExtension
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? RoomID { get; set; }
		public virtual string FacilityName { get; set; }
		public virtual string FaciliTypeName { get; set; }
		public virtual int? IsAllAvailable { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual GuestRoom GuestRoom { get; set; }
	}

    /// <summary>
    /// A class which represents the ACC table.
    /// </summary>
	[Table("ACC")]
	public partial class ACC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the RoomPlanBookRuleMapping table.
    /// </summary>
	[Table("RoomPlanBookRuleMapping")]
	public partial class RoomPlanBookRuleMapping
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? BookRuleId { get; set; }
		public virtual int? RatePlanId { get; set; }
		public virtual string Parameters { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual BookRule BookRule { get; set; }
		public virtual RatePlan RatePlan { get; set; }
	}

    /// <summary>
    /// A class which represents the Address table.
    /// </summary>
	[Table("Address")]
	public partial class Address
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string HotelID { get; set; }
		public virtual string AddressLine { get; set; }
		public virtual string CityName { get; set; }
		public virtual string PostalCode { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual Hotel Hotel { get; set; }
		public virtual IEnumerable<AddressExtension> AddressExtension { get; set; }
	}

    /// <summary>
    /// A class which represents the RTC table.
    /// </summary>
	[Table("RTC")]
	public partial class RTC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the AddressExtension table.
    /// </summary>
	[Table("AddressExtension")]
	public partial class AddressExtension
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? AddressID { get; set; }
		public virtual string Description { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual Address Address { get; set; }
	}

    /// <summary>
    /// A class which represents the SEG table.
    /// </summary>
	[Table("SEG")]
	public partial class SEG
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
		public virtual IEnumerable<CategoryCodeHotelMapping> CategoryCodeHotelMapping { get; set; }
	}

    /// <summary>
    /// A class which represents the ADT table.
    /// </summary>
	[Table("ADT")]
	public partial class ADT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the TextItem table.
    /// </summary>
	[Table("TextItem")]
	public partial class TextItem
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string HotelId { get; set; }
		public virtual int? Category { get; set; }
		public virtual string DescriptionText { get; set; }
		public virtual DateTime? LastModityTime { get; set; }
		public virtual Hotel Hotel { get; set; }
	}

    /// <summary>
    /// A class which represents the AIC table.
    /// </summary>
	[Table("AIC")]
	public partial class AIC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the UIT table.
    /// </summary>
	[Table("UIT")]
	public partial class UIT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the AMC table.
    /// </summary>
	[Table("AMC")]
	public partial class AMC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the UOM table.
    /// </summary>
	[Table("UOM")]
	public partial class UOM
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
		public virtual IEnumerable<RefPoint> RefPoint { get; set; }
	}

    /// <summary>
    /// A class which represents the ARC table.
    /// </summary>
	[Table("ARC")]
	public partial class ARC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the Zone table.
    /// </summary>
	[Table("Zone")]
	public partial class Zone
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual IEnumerable<ZoneHotelMapping> ZoneHotelMapping { get; set; }
	}

    /// <summary>
    /// A class which represents the AwardType table.
    /// </summary>
	[Table("AwardType")]
	public partial class AwardType
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the ZoneHotelMapping table.
    /// </summary>
	[Table("ZoneHotelMapping")]
	public partial class ZoneHotelMapping
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? ZoneID { get; set; }
		public virtual string HotelID { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual Zone Zone { get; set; }
		public virtual Hotel Hotel { get; set; }
	}

    /// <summary>
    /// A class which represents the BaseByGuestAmt table.
    /// </summary>
	[Table("BaseByGuestAmt")]
	public partial class BaseByGuestAmt
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? RateId { get; set; }
		public virtual decimal? AmountBeforeTax { get; set; }
		public virtual string CurrencyCode { get; set; }
		public virtual int? NumberOfGuests { get; set; }
		public virtual decimal? ListPrice { get; set; }
		public virtual decimal? OtherCurrency { get; set; }
		public virtual string OtherCurrencyCode { get; set; }
		public virtual string LastModifyTime { get; set; }
		public virtual Rate Rate { get; set; }
	}

    /// <summary>
    /// A class which represents the BED table.
    /// </summary>
	[Table("BED")]
	public partial class BED
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the __RefactorLog table.
    /// </summary>
	[Table("__RefactorLog")]
	public partial class RefactorLog
	{
		[Key]
		public virtual Guid OperationKey { get; set; }
	}

    /// <summary>
    /// A class which represents the BookRule table.
    /// </summary>
	[Table("BookRule")]
	public partial class BookRule
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual IEnumerable<RoomPlanBookRuleMapping> RoomPlanBookRuleMapping { get; set; }
	}

    /// <summary>
    /// A class which represents the BUS table.
    /// </summary>
	[Table("BUS")]
	public partial class BUS
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the RefPoint table.
    /// </summary>
	[Table("RefPoint")]
	public partial class RefPoint
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string HotelID { get; set; }
		public virtual decimal? Distance { get; set; }
		public virtual int? UOMID { get; set; }
		public virtual string Name { get; set; }
		public virtual int? REFINT { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual Hotel Hotel { get; set; }
		public virtual UOM UOM { get; set; }
	}

    /// <summary>
    /// A class which represents the CancelPenalty table.
    /// </summary>
	[Table("CancelPenalty")]
	public partial class CancelPenalty
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? RateId { get; set; }
		public virtual DateTime? Start { get; set; }
		public virtual DateTime? End { get; set; }
		public virtual decimal? AmountPercent { get; set; }
		public virtual string CurrencyCode { get; set; }
		public virtual decimal? OtherCurrencyAmount { get; set; }
		public virtual string OtherCurrencyCode { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual Rate Rate { get; set; }
	}

    /// <summary>
    /// A class which represents the CategoryCodeHotelMapping table.
    /// </summary>
	[Table("CategoryCodeHotelMapping")]
	public partial class CategoryCodeHotelMapping
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string HotelId { get; set; }
		public virtual int? SEGID { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual Hotel Hotel { get; set; }
		public virtual SEG SEG { get; set; }
	}

    /// <summary>
    /// A class which represents the CCT table.
    /// </summary>
	[Table("CCT")]
	public partial class CCT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the CDT table.
    /// </summary>
	[Table("CDT")]
	public partial class CDT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the CFC table.
    /// </summary>
	[Table("CFC")]
	public partial class CFC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the CHG table.
    /// </summary>
	[Table("CHG")]
	public partial class CHG
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the CXR table.
    /// </summary>
	[Table("CXR")]
	public partial class CXR
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the DEC table.
    /// </summary>
	[Table("DEC")]
	public partial class DEC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the DNA table.
    /// </summary>
	[Table("DNA")]
	public partial class DNA
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the DSP table.
    /// </summary>
	[Table("DSP")]
	public partial class DSP
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the DTB table.
    /// </summary>
	[Table("DTB")]
	public partial class DTB
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the EAT table.
    /// </summary>
	[Table("EAT")]
	public partial class EAT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the EWT table.
    /// </summary>
	[Table("EWT")]
	public partial class EWT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the EXH table.
    /// </summary>
	[Table("EXH")]
	public partial class EXH
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the Fee table.
    /// </summary>
	[Table("Fee")]
	public partial class Fee
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int RateId { get; set; }
		public virtual int? Code { get; set; }
		public virtual decimal? Amount { get; set; }
		public virtual string CurrencyCode { get; set; }
		public virtual int? ChargeUnit { get; set; }
		public virtual string DescriptionText { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual Rate Rate { get; set; }

	}

    /// <summary>
    /// A class which represents the FMT table.
    /// </summary>
	[Table("FMT")]
	public partial class FMT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the FQC table.
    /// </summary>
	[Table("FQC")]
	public partial class FQC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the FTT table.
    /// </summary>
	[Table("FTT")]
	public partial class FTT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the GRI table.
    /// </summary>
	[Table("GRI")]
	public partial class GRI
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the GuaranteePolicy table.
    /// </summary>
	[Table("GuaranteePolicy")]
	public partial class GuaranteePolicy
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? RateId { get; set; }
		public virtual int? GuaranteeCode { get; set; }
		public virtual DateTime? HoldTime { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual Rate Rate { get; set; }
	}

    /// <summary>
    /// A class which represents the GuestRoom table.
    /// </summary>
	[Table("GuestRoom")]
	public partial class GuestRoom
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual string HotelID { get; set; }
		public virtual int? StandardOccupancy { get; set; }
		public virtual string Size { get; set; }
		public virtual int? RoomTypeCode { get; set; }
		public virtual string Floor { get; set; }
		public virtual int? BedTypeCode { get; set; }
		public virtual int? Quantity { get; set; }
		public virtual string FeatureDescription { get; set; }
		public virtual int? InvBlockCode { get; set; }
		public virtual int? NonSmoking { get; set; }
		public virtual string RoomSize { get; set; }
		public virtual int? HasWindow { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual Hotel Hotel { get; set; }
		public virtual IEnumerable<RMARoomMapping> RMARoomMapping { get; set; }
		public virtual IEnumerable<RoomExtension> RoomExtension { get; set; }
	}

    /// <summary>
    /// A class which represents the HAC table.
    /// </summary>
	[Table("HAC")]
	public partial class HAC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
		public virtual IEnumerable<HACHATMapping> HACHATMapping { get; set; }
	}

    /// <summary>
    /// A class which represents the HACHATMapping table.
    /// </summary>
	[Table("HACHATMapping")]
	public partial class HACHATMapping
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? HACID { get; set; }
		public virtual int? HATID { get; set; }
		public virtual string HotelID { get; set; }
		public virtual DateTime? LastModifyTine { get; set; }
		public virtual HAC HAC { get; set; }
		public virtual HAT HAT { get; set; }
		public virtual Hotel Hotel { get; set; }
	}

    /// <summary>
    /// A class which represents the HAT table.
    /// </summary>
	[Table("HAT")]
	public partial class HAT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
		public virtual IEnumerable<HACHATMapping> HACHATMapping { get; set; }
	}

    /// <summary>
    /// A class which represents the HOC table.
    /// </summary>
	[Table("HOC")]
	public partial class HOC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the Hotel table.
    /// </summary>
	[Table("Hotel")]
	public partial class Hotel
	{
		[Key]
		public virtual string Id { get; set; }
		public virtual int? HotelCode { get; set; }
		public virtual int? BrandCode { get; set; }
		public virtual int? HotelCityCode { get; set; }
		public virtual string HotelName { get; set; }
		public virtual int? AreaID { get; set; }
		public virtual DateTime? WhenBuilt { get; set; }
		public virtual DateTime? LastUpdated { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual byte[] Timestamp { get; set; }
		public virtual IEnumerable<Address> Address { get; set; }
		public virtual IEnumerable<TextItem> TextItem { get; set; }
		public virtual IEnumerable<ZoneHotelMapping> ZoneHotelMapping { get; set; }
		public virtual IEnumerable<RefPoint> RefPoint { get; set; }
		public virtual IEnumerable<CategoryCodeHotelMapping> CategoryCodeHotelMapping { get; set; }
		public virtual IEnumerable<GuestRoom> GuestRoom { get; set; }
		public virtual IEnumerable<HACHATMapping> HACHATMapping { get; set; }
		public virtual IEnumerable<HotelAwardMapping> HotelAwardMapping { get; set; }
		public virtual IEnumerable<ImageItem> ImageItem { get; set; }
		public virtual IEnumerable<Policy> Policy { get; set; }
		public virtual IEnumerable<PolicyInfo> PolicyInfo { get; set; }
		public virtual IEnumerable<Position> Position { get; set; }
	}

    /// <summary>
    /// A class which represents the HotelAwardMapping table.
    /// </summary>
	[Table("HotelAwardMapping")]
	public partial class HotelAwardMapping
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? AwardID { get; set; }
		public virtual string HotelID { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual decimal? Rating { get; set; }
		public virtual Hotel Hotel { get; set; }
	}

    /// <summary>
    /// A class which represents the HST table.
    /// </summary>
	[Table("HST")]
	public partial class HST
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the ImageItem table.
    /// </summary>
	[Table("ImageItem")]
	public partial class ImageItem
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string HotelId { get; set; }
		public virtual int? Category { get; set; }
		public virtual string URL { get; set; }
		public virtual string Description { get; set; }
		public virtual int? InvBlockCode { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual Hotel Hotel { get; set; }
	}

    /// <summary>
    /// A class which represents the INF table.
    /// </summary>
	[Table("INF")]
	public partial class INF
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the LOC table.
    /// </summary>
	[Table("LOC")]
	public partial class LOC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the MCC table.
    /// </summary>
	[Table("MCC")]
	public partial class MCC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the OTC table.
    /// </summary>
	[Table("OTC")]
	public partial class OTC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the PAC table.
    /// </summary>
	[Table("PAC")]
	public partial class PAC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the PCT table.
    /// </summary>
	[Table("PCT")]
	public partial class PCT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the PIC table.
    /// </summary>
	[Table("PIC")]
	public partial class PIC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the PMT table.
    /// </summary>
	[Table("PMT")]
	public partial class PMT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the Policy table.
    /// </summary>
	[Table("Policy")]
	public partial class Policy
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string HotelID { get; set; }
		public virtual string Key { get; set; }
		public virtual string Value { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual Hotel Hotel { get; set; }
	}

    /// <summary>
    /// A class which represents the PolicyInfo table.
    /// </summary>
	[Table("PolicyInfo")]
	public partial class PolicyInfo
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string HotelId { get; set; }
		public virtual string CheckIn { get; set; }
		public virtual string CheckOut { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual Hotel Hotel { get; set; }
	}

    /// <summary>
    /// A class which represents the Position table.
    /// </summary>
	[Table("Position")]
	public partial class Position
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string HotelID { get; set; }
		public virtual decimal? Latitude { get; set; }
		public virtual decimal? Longitude { get; set; }
		public virtual int? PositionTypeCode { get; set; }
		public virtual DateTime? LastMofifyTime { get; set; }
		public virtual Hotel Hotel { get; set; }
	}

    /// <summary>
    /// A class which represents the PRT table.
    /// </summary>
	[Table("PRT")]
	public partial class PRT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the PRX table.
    /// </summary>
	[Table("PRX")]
	public partial class PRX
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the PST table.
    /// </summary>
	[Table("PST")]
	public partial class PST
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the PTT table.
    /// </summary>
	[Table("PTT")]
	public partial class PTT
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the QCC table.
    /// </summary>
	[Table("QCC")]
	public partial class QCC
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the QST table.
    /// </summary>
	[Table("QST")]
	public partial class QST
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? LastModiyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the Rate table.
    /// </summary>
	[Table("Rate")]
	public partial class Rate
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? RatePlanId { get; set; }
		public virtual int? NumberOfUnits { get; set; }
		public virtual DateTime? Start { get; set; }
		public virtual DateTime? End { get; set; }
		public virtual bool? IsInstantConfirm { get; set; }
		public virtual string Status { get; set; }
		public virtual bool? IsBreakfast { get; set; }
		public virtual int? BreakfastNumber { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual RatePlan RatePlan { get; set; }
		public virtual IEnumerable<Fee> Fee { get; set; }
		public virtual IEnumerable<BaseByGuestAmt> BaseByGuestAmt { get; set; }
		public virtual IEnumerable<CancelPenalty> CancelPenalty { get; set; }

		public virtual IEnumerable<GuaranteePolicy> GuaranteePolicy { get; set; }
		public virtual IEnumerable<RateExtension> RateExtensions { get; set; }
	}

    /// <summary>
    /// A class which represents the RateExtensions table.
    /// </summary>
	[Table("RateExtensions")]
	public partial class RateExtension
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? RateId { get; set; }
		public virtual DateTime? StartPeriod { get; set; }
		public virtual DateTime? EndPeriod { get; set; }
		public virtual string ProgramName { get; set; }
		public virtual decimal? Amount { get; set; }
		public virtual string CurrencyCode { get; set; }
		public virtual int? Code { get; set; }
		public virtual string DescriptionText { get; set; }
		public virtual DateTime? LastModifyTime { get; set; }
		public virtual Rate Rate { get; set; }
	}

}
