//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public Address()
        {
            this.AddressExtensions = new HashSet<AddressExtension>();
        }
    
        public int Id { get; set; }
        public string HotelID { get; set; }
        public string AddressLine { get; set; }
        public string CityName { get; set; }
        public string PostalCode { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    
        public virtual ICollection<AddressExtension> AddressExtensions { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
