//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int Id { get; set; }
        public int RateId { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<int> ChargeUnit { get; set; }
        public string DescriptionText { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    
        public virtual Rate Rate { get; set; }
        public virtual Rate Rate1 { get; set; }
    }
}
