//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAT
    {
        public HAT()
        {
            this.HACHATMappings = new HashSet<HACHATMapping>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastModiyTime { get; set; }
    
        public virtual ICollection<HACHATMapping> HACHATMappings { get; set; }
    }
}
