//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offer
    {
        public int Id { get; set; }
        public Nullable<int> ratePlanId { get; set; }
        public Nullable<int> OfferCode { get; set; }
        public string OfferDescription { get; set; }
        public Nullable<int> NightsRequired { get; set; }
        public Nullable<int> NightsDiscounted { get; set; }
        public string DiscountPattern { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
