//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferRule
    {
        public int Id { get; set; }
        public Nullable<int> OfferId { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public string RestrictionType { get; set; }
        public Nullable<int> RestrictionDateCode { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    }
}
