//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public Rate()
        {
            this.BaseByGuestAmts = new HashSet<BaseByGuestAmt>();
            this.CancelPenalties = new HashSet<CancelPenalty>();
            this.Fees = new HashSet<Fee>();
            this.Fees1 = new HashSet<Fee>();
            this.GuaranteePolicies = new HashSet<GuaranteePolicy>();
            this.RateExtensions = new HashSet<RateExtension>();
        }
    
        public int Id { get; set; }
        public Nullable<int> RatePlanId { get; set; }
        public Nullable<int> NumberOfUnits { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<bool> IsInstantConfirm { get; set; }
        public string Status { get; set; }
        public Nullable<bool> IsBreakfast { get; set; }
        public Nullable<int> BreakfastNumber { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    
        public virtual ICollection<BaseByGuestAmt> BaseByGuestAmts { get; set; }
        public virtual ICollection<CancelPenalty> CancelPenalties { get; set; }
        public virtual ICollection<Fee> Fees { get; set; }
        public virtual ICollection<Fee> Fees1 { get; set; }
        public virtual ICollection<GuaranteePolicy> GuaranteePolicies { get; set; }
        public virtual ICollection<RateExtension> RateExtensions { get; set; }
        public virtual RatePlan RatePlan { get; set; }
    }
}
