//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RMA
    {
        public RMA()
        {
            this.RMARoomMappings = new HashSet<RMARoomMapping>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> LastModiyTime { get; set; }
    
        public virtual ICollection<RMARoomMapping> RMARoomMappings { get; set; }
    }
}
