//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomExtension
    {
        public int Id { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string FacilityName { get; set; }
        public string FaciliTypeName { get; set; }
        public Nullable<int> IsAllAvailable { get; set; }
        public Nullable<System.DateTime> LastMofifyTime { get; set; }
    
        public virtual GuestRoom GuestRoom { get; set; }
    }
}
